server:
  port: 8082
#private String lastName;
#private Integer age;
#private Boolean boss;
#private Date birth;
#private Map<String, Object> maps;
#private List<Object> lists;
#private Dog dog;
person:
#  ""   会输出 换行
  last-name: "李小龙\nkkk 赵丽颖"
  age: ${random.int}
  boss: false
  birth: 1901/01/01
#  行内写法
#  maps: {k1: ,k2: /nkkk}
  maps:
    k1: v1
    k2: v2
#  行内写法
#  lists: [1,12]
  lists:
    - 1
    - 12
  dog:
#    单引号 写啥就输出啥(进行了转义操作)
#    什么也不加  是啥就输出啥
    name: ${person.hello:使用鸟默认值}'李小龙\nkkk 赵丽颖'
    age: 5

