spring:
  datasource:
    url: jdbc:mysql://localhost:3306/t_imgs
    username: root
    password: kk
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat,wall
    tomcat:
      max-active: 10

  druid:
#    filters: stat,wall,slf4j  #所有开启的功能

