server:
  port: 8082
person:
  last-name: 开发环境
  age: ${random.int}
  boss: false
  birth: 1901/01/01
  maps:
    k1: v1
    k2: v2
  lists:
    - 1
    - 12
  dog:
    name: ${person.hello:开发版本}
    age: 5
